version: '3'
services:
  database:
    image: postgres
    environment:
      PGDATA: /app/data
      POSTGRES_USER: postgres
    volumes:
      - dbdata:/app/data

  default: &default
    image: zenfit
    build:
      context: .
    volumes:
      - $PWD:/app
    ports:
      - "3001:3001"
      - "9292:9292"
    depends_on:
      - database
  api:
    <<: *default
  specs:
    <<: *default
    command:
      - rspec

volumes:
  dbdata:
