default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: database

development:
  <<: *default
  database: zenfit-api_development
  #password:

test:
  <<: *default
  database: zenfit-api_test

production:
  <<: *default
  database: zenfit-api_production
  username: zenfit-api
  password: <%= ENV['ZENFIT-API_DATABASE_PASSWORD'] %>
